let cards = [
  {
    artName: "That Animation",
    pageLink: "./Art/MaKloudz/index.html",
    imageLink: "./Art/MaKloudz/dat-animation.gif",
    author: "Blessing Mutava",
    githubLink: "https://github.com/MaKloudz",
  },
  {
    artName: "animatron",
    pageLink: "./Art/animatron/index.html",
    imageLink: "./Art/animatron/trance.gif",
    author: "nick981837",
    githubLink: "https://github.com/nick981837",
  },
  {
    artName: "ZTM Animation",
    pageLink: "./Art/EricPuskas/index.html",
    imageLink: "./Art/EricPuskas/index.gif",
    author: "Eric Puskas",
    githubLink: "https://github.com/EricPuskas",
  },
  {
    artName: "LSD Rainbow Trip: Phase 1",
    pageLink: "./Art/AbsMechanik/index.html",
    imageLink: "./Art/AbsMechanik/AbsMechanik_Animation.gif",
    author: "AbsMechanik",
    githubLink: "https://github.com/AbsMechanik",
  },
  {
    artName: "Christmas Lights",
    pageLink: "./Art/Futuregit/index.html",
    imageLink: "./Art/Futuregit/Christmas-Lights.gif",
    author: "Futuregit",
    githubLink: "https://github.com/Futuregit",
  },
  {
    artName: "space zoo",
    pageLink: "./Art/space_zoo/index.html",
    imageLink: "./Art/space_zoo/space_zoo.gif",
    author: "yuwenGithub",
    githubLink: "https://github.com/yuwenGithub",
  },
  {
    artName: "Fruit Dancing",
    pageLink: "./Art/carlacentenor/index.html",
    imageLink: "./Art/carlacentenor/fruit.gif",
    author: "carlacentenor",
    githubLink: "https://github.com/carlacentenor",
  },
  {
    artName: "eyes",
    pageLink: "./Art/eyes/index.html",
    imageLink: "./Art/eyes/eyes.gif",
    author: "yuwenGithub",
    githubLink: "https://github.com/yuwenGithub",
  },
  {
    artName: "Spooktober Hacktoberfest",
    pageLink: "./Art/FredAmartey/index.html",
    imageLink: "./Art/FredAmartey/thumbnaill.gif",
    author: "Fred Amartey",
    githubLink: "https://github.com/FredAmartey",
  },
  {
    artName: "Star Wars?",
    pageLink: "./Art/henryvalbuena/index.html",
    imageLink: "./Art/henryvalbuena/index.gif",
    author: "Henry Valbuena",
    githubLink: "https://github.com/henryvalbuena",
  },
  {
    artName: "UFO",
    pageLink: "./Art/UFO/index.html",
    imageLink: "./Art/UFO/UFO.png",
    author: "Abhinav Singh @abhinav9910",
    githubLink: "https://github.com/abhinav9910",
  },
  {
    artName: "The Ripple",
    pageLink: "./Art/Anmol2/index.html",
    imageLink: "./Art/Anmol2/ripple.png",
    author: "Anmol",
    githubLink: "https://github.com/Anmol270900",
  },
  {
    artName: "Rainbow loader",
    pageLink: "./Art/ka-hn/rainbow.html",
    imageLink: "./Art/ka-hn/rainbow.gif",
    author: "Karim Hussain",
    githubLink: "https://github.com/ka-hn",
  },
  {
    artName: "Action Cam",
    pageLink: "./Art/Donovan/index.html",
    imageLink: "./Art/Donovan/pureCSS-animation.gif",
    author: "Donovan Hunter",
    githubLink: "https://github.com/dhdcode",
  },
  {
    artName: "The Sun",
    pageLink: "./Art/Anmol/index.html",
    imageLink: "./Art/Anmol/sun.png",
    author: "Anmol",
    githubLink: "https://github.com/Anmol270900",
  },
  {
    artName: "Flashing Pumpkin",
    pageLink: "./Art/KatrinaRose14/index.html",
    imageLink: "./Art/KatrinaRose14/FlashingPumpkin.gif",
    author: "Katrina Yates",
    githubLink: "https://github.com/KatrinaRose14",
  },
  {
    artName: "Flipbox",
    pageLink: "./Art/Prasheel/index.html",
    imageLink: "./Art/Prasheel/flip.gif",
    author: "Prasheel Soni",
    githubLink: "https://github.com/ps011",
  },
  {
    artName: "2019 Wave",
    pageLink: "./Art/chris-aqui/index.html",
    imageLink: "./Art/chris-aqui/2019-jump.gif",
    author: "Christine Aqui",
    githubLink: "https://github.com/christine-aqui",
  },
  {
    artName: "Hover Button Animation",
    pageLink: "./Art/Vipul/hover.html",
    imageLink: "./Art/Vipul/Screenshot2.png",
    author: "Vipul",
    githubLink: "https://github.com/vipuljain08",
  },
  {
    artName: "Start From Zero",
    pageLink: "./Art/Robihdy/index.html",
    imageLink: "./Art/Robihdy/start-from-zero.png",
    author: "Robihdy",
    githubLink: "https://github.com/Robihdy",
  },
  {
    artName: "Local Host metaphor",
    pageLink: "./Art/Akbar-Cyber/index.html",
    imageLink: "./Art/Prateek/localhost.png",
    author: "Prateek",
    githubLink: "https://github.com/prateekpatrick",
  },
  {
    artName: "Akbar-Cyber",
    pageLink: "./Art/Akbar-Cyber/index.html",
    imageLink: "./Art/Akbar-Cyber/akbar.gif",
    author: "Akbar",
    githubLink: "https://github.com/Akbar-Cyber",
  },
  {
    artName: "Sliding Lines",
    pageLink: "./Art/erics0n/sliding-lines/index.html",
    imageLink: "./Art/erics0n/sliding-lines/image.gif",
    author: "erics0n",
    githubLink: "https://github.com/erics0n",
  },
  {
    artName: "Triangle",
    pageLink: "./Art/Joy/triangle/triangle.html",
    imageLink: "./Art/Joy/triangle/triangle.gif",
    author: "Joy",
    githubLink: "https://github.com/royranger",
  },
  {
    artName: "Cube",
    pageLink: "./Art/Joy/cube/cube.html",
    imageLink: "./Art/Joy/cube/cube.gif",
    author: "Joy",
    githubLink: "https://github.com/royranger",
  },
  {
    artName: "Burger Menu",
    pageLink: "./Art/mctrl/burger.html",
    imageLink: "./Art/mctrl/burger.gif",
    author: "Martina",
    githubLink: "https://github.com/mctrl",
  },
  {
    artName: "Square Loader",
    pageLink: "./Art/Hemant/index.html",
    imageLink: "./Art/Hemant/loader.gif",
    author: "Hemant Garg",
    githubLink: "https://github.com/hemant-garg",
  },
  {
    artName: "wake up, neo...",
    pageLink: "./Art/samirjouni/TributeToTheMatrix.html",
    imageLink: "./Art/samirjouni/sample.gif",
    author: "Samir Jouni",
    githubLink: "https://github.com/samirjouni",
  },
  {
    artName: "Tribute To COD4MW",
    pageLink: "./Art/samirjouni2/index.html",
    imageLink: "./Art/samirjouni2/sample.gif",
    author: "Samir Jouni",
    githubLink: "https://github.com/samirjouni",
  },
  {
    artName: "Planet",
    pageLink: "./Art/ArthurDoom/planet.html",
    imageLink: "./Art/ArthurDoom/planet.gif",
    author: "ArthurDoom",
    githubLink: "https://github.com/ArthurDoom",
  },
  {
    artName: "SquarPy",
    pageLink: "./Art/Utkarsh/index.html",
    imageLink: "./Art/Utkarsh/hack.gif",
    author: "utkarsh",
    githubLink: "https://github.com/Utkarsh2604",
  },
  {
    artName: "Circle",
    pageLink: "./Art/Oliver/Circle.html",
    imageLink: "./Art/Oliver/circle.gif",
    author: "Oliver",
    githubLink: "https://github.com/oliver-gomes",
  },
  {
    artName: "Ellipse Loader",
    pageLink: "./Art/VaibhavKhulbe/EllipseLoader.html",
    imageLink: "./Art/VaibhavKhulbe/ellipseLoader.gif",
    author: "Vaibhav Khulbe",
    githubLink: "https://github.com/Kvaibhav01",
  },
  {
    artName: "Simple Loader",
    pageLink: "./Art/soumsps/simpleload.html",
    imageLink: "./Art/soumsps/sample.gif",
    author: "Soumendu Sinha",
    githubLink: "https://github.com/soumsps",
  },
  {
    artName: "Rollodex",
    pageLink: "./Art/Shruti/rolling.html",
    imageLink: "./Art/Shruti/rolling.gif",
    author: "Shruti",
    githubLink: "https://github.com/shruti49",
  },
  {
    artName: "Cute Cat",
    pageLink: "./Art/Alghi/cat.html",
    imageLink: "./Art/Alghi/cat.gif",
    author: "Alghi",
    githubLink: "https://github.com/darklordace",
  },
  {
    artName: "ZtM Text",
    pageLink: "./Art/Di4iMoRtAl/ZtM_text_animation.html",
    imageLink: "./Art/Di4iMoRtAl/ZtM_animation.gif",
    author: "Di4iMoRtAl",
    githubLink: "https://github.com/dppeykov",
  },
  {
    artName: "Circles",
    pageLink: "./Art/Bhuvana/circles.html",
    imageLink: "./Art/Bhuvana/circles.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Bird",
    pageLink: "./Art/Bhuvana/bird.html",
    imageLink: "./Art/Bhuvana/bird.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Loader",
    pageLink: "./Art/Bhuvana/loader.html",
    imageLink: "./Art/Bhuvana/loader.gif",
    author: "Bhuvana",
    githubLink: "https://github.com/bhuvana-guna",
  },
  {
    artName: "Simple blinking loading circles",
    pageLink: "./Art/Rahul/index.html",
    imageLink: "./Art/Rahul/loading.gif",
    author: "Rahul",
    githubLink: "https://github.com/kohli6010",
  },
  {
    artName: "Css Pulse",
    pageLink: "./Art/Aszmel/pulse.html",
    imageLink: "./Art/Aszmel/css_pulse.gif",
    author: "Aszmel",
    githubLink: "https://github.com/Aszmel",
  },
  {
    artName: "Circle Bounce",
    pageLink: "./Art/Edmund/index.html",
    imageLink: "./Art/Edmund/circle-bounce.gif",
    author: "Edmund",
    githubLink: "https://github.com/edmund1645",
  },
  {
    artName: "Heart Beating",
    pageLink: "./Art/Regem/index.html",
    imageLink: "./Art/Regem/heart.jpg",
    author: "Regem",
    githubLink: "https://github.com/GemzBond",
  },
  {
    artName: "Fading Circles",
    pageLink: "./Art/Ankit/fadeCircle.html",
    imageLink: "./Art/Ankit/fadeCircles.png",
    author: "Ankit Srivastava",
    githubLink: "https://github.com/a18nov",
  },
  {
    artName: "Hacktoberfest 2019",
    pageLink: "./Art/jpk3lly/animation.html",
    imageLink: "./Art/jpk3lly/JPs_Animation_GIF.gif",
    author: "jpk3lly",
    githubLink: "https://github.com/jpk3lly",
  },
  {
    artName: "Name Rotator",
    pageLink: "./Art/Meet/name.html",
    imageLink: "./Art/Meet/name.gif",
    author: "Meet",
    githubLink: "https://github.com/Meet1103",
  },
  {
    artName: "Ball Rotator",
    pageLink: "./Art/Bibekpreet/index.html",
    imageLink: "./Art/Bibekpreet/ball.gif",
    author: "Bibekpreet",
    githubLink: "https://github.com/bibekpreet99",
  },
  {
    artName: "ephiphany",
    pageLink: "./Art/OctavianIlies/index.html",
    imageLink: "./Art/OctavianIlies/ephiphany.gif",
    author: "OctavianIlies",
    githubLink: "https://github.com/OctavianIlies",
  },
  {
    artName: "Loading",
    pageLink: "./Art/jh1992jh/loading.html",
    imageLink: "./Art/jh1992jh/loading.gif",
    author: "jh1992jh",
    githubLink: "https://github.com/jh1992jh",
  },
  {
    artName: "ZTM Colors",
    pageLink: "./Art/Godnon/index.html",
    imageLink: "./Art/Godnon/ZTMcAnim.gif",
    author: "Godnon",
    githubLink: "https://github.com/godnondsilva",
  },
  {
    artName: "Hover Effect",
    pageLink: "./Art/Shubhankar/index.html",
    imageLink: "./Art/Shubhankar/hackoctober.gif",
    author: "Shubhankar",
    githubLink: "https://github.com/shubhdwiv12",
  },
  {
    artName: "Bouncing Fading Circles",
    pageLink: "./Art/AyoubIssaad/index.html",
    imageLink: "./Art/AyoubIssaad/BouncingFadingCircles.gif",
    author: "AyoubIssaad",
    githubLink: "https://github.com/AyoubIssaad",
  },
  {
    artName: "5 balls preloader",
    pageLink: "./Art/Nnaji-Victor/index.html",
    imageLink: "./Art/Nnaji-Victor/5_balls.gif",
    author: "Nnaji Victor",
    githubLink: "https://github.com/Nnaji-Victor",
  },
  {
    artName: "ZTM Bouncer",
    pageLink: "./Art/Josia/bouncer.html",
    imageLink: "./Art/Josia/ztmbouncer.gif",
    author: "Josia Rodriguez",
    githubLink: "https://github.com/josiarod",
  },
  {
    artName: "Hacktober loading animation",
    pageLink: "./Art/mehul1011/index.html",
    imageLink: "./Art/mehul1011/loading.gif",
    author: "Mehul1011",
    githubLink: "https://github.com/mehul1011",
  },
  {
    artName: "Loading Dots",
    pageLink: "./Art/devSergiu/index.html",
    imageLink: "./Art/devSergiu/loading.gif",
    author: "devSergiu",
    githubLink: "https://github.com/devsergiu",
  },
  {
    artName: "TypeWriter effect",
    pageLink: "./Art/Sidharth/Typing_Text.html",
    imageLink: "./Art/Sidharth/type_writer.gif",
    author: "Sidharth",
    githubLink: "https://github.com/Sidharth98",
  },
  {
    artName: "Blue Spin",
    pageLink: "./Art/JamesW/index.html",
    imageLink: "./Art/JamesW/hacktober_spin.gif",
    author: "James Whitney",
    githubLink: "https://github.com/jameswhitney",
  },
  {
    artName: "Loading Animation",
    pageLink: "./Art/Sidharth/Loading.html",
    imageLink: "./Art/Sidharth/Loading.gif",
    author: "Sidharth",
    githubLink: "https://github.com/Sidharth98",
  },
  {
    artName: "Rotation",
    pageLink: "./Art/alenanog/index.html",
    imageLink: "./Art/alenanog/rotation.gif",
    author: "Alena A.",
    githubLink: "https://github.com/alenanog",
  },
  {
    artName: "Colors in your life",
    pageLink: "./Art/Atipahy/colors.html",
    imageLink: "./Art/Atipahy/colors.png",
    author: "Christos Chr",
    githubLink: "https://github.com/atipaHy",
  },
  {
    artName: "Orb",
    pageLink: "./Art/Jkbicbic/orb.html",
    imageLink: "./Art/Jkbicbic/orb.gif",
    author: "John Kennedy Bicbic",
    githubLink: "https://github.com/jkbicbic",
  },
  {
    artName: "Charging...",
    pageLink: "./Art/Afraz/charging.html",
    imageLink: "./Art/Afraz/charging.gif",
    author: "Afraz",
    githubLink: "https://github.com/afrazz",
  },
  {
    artName: "Charging...",
    pageLink: "./Art/DepStep/depstep.html",
    imageLink: "./Art/DepStep/depstep.gif",
    author: "DepStep",
    githubLink: "https://github.com/stephD",
  },
  {
    artName: "Dancing Ball...",
    pageLink: "./Art/DaveFres/index.html",
    imageLink: "./Art/DaveFres/ball.gif",
    author: "DaveFres",
    githubLink: "https://github.com/DaveFres",
  },
  {
    artName: "animatron",
    pageLink: "./Art/animatron/index.html",
    imageLink: "./Art/animatron/trance.gif",
    author: "jomahay",
    githubLink: "https://github.com/jomahay",
  },
  {
    artName: "Sunshine",
    pageLink: "./Art/Pavelisp/sunshine.html",
    imageLink: "./Art/Pavelisp/sunshine.gif",
    author: "Pavel Isp",
    githubLink: "https://github.com/pavelisp",
  },
  {
    artName: "SoundBoxes",
    pageLink: "./Art/Hbarang/SoundBox.html",
    imageLink: "./Art/Hbarang/SoundBoxAnimation.gif",
    author: "Hbarang",
    githubLink: "https://github.com/hbarang",
  },
  {
    artName: "Cheshire",
    pageLink: "./Art/Ckanelin/index.html",
    imageLink: "./Art/Ckanelin/Cheshire.gif",
    author: "Ckanelin",
    githubLink: "https://github.com/ckanelin",
  },
  {
    artName: "Disappear",
    pageLink: "./Art/Stacy/index.html",
    imageLink: "./Art/Stacy/disappear.gif",
    author: "Stacy",
    githubLink: "https://github.com/stacyholtz6",
  },
  {
    artName: "Ellipse Spinner",
    pageLink: "./Art/Sabina/ellipse_spinner.html",
    imageLink: "./Art/Sabina/ellipse_spinner.png",
    author: "Sabina Abbasova",
    githubLink: "https://github.com/sabina929",
  },
  {
    artName: "NightSky",
    pageLink: "./Art/AndyS/index.html",
    imageLink: "./Art/AndyS/Capture.GIF",
    author: "AndyS",
    githubLink: "https://github.com/AndyS1988",
  },
  {
    artName: "Hungry",
    pageLink: "./Art/diegchav/index.html",
    imageLink: "./Art/diegchav/hungry.gif",
    author: "Diego Chz",
    githubLink: "https://github.com/diegchav",
  },
  {
    artName: "Hover Text Animation",
    pageLink: "./Art/AyoubIssaad2/index.html",
    imageLink: "./Art/AyoubIssaad2/hoverTextAnimation.gif",
    author: "AyoubIssaad",
    githubLink: "https://github.com/AyoubIssaad",
  },
  {
    artName: "Colorize",
    pageLink: "./Art/JimBratsos/colorize.html",
    imageLink: "./Art/JimBratsos/Colorize.gif",
    author: "Jim Bratsos",
    githubLink: "https://github.com/JimBratsos",
  },
  {
    artName: "Hacktober Spooktacular",
    pageLink: "Art/Elex/index.html",
    imageLink: ["./Art/Elex/hhs.gif"],
    author: "William Poisel (LordCobra)",
    githubLink: "https://github.com/epoisel",
  },
  {
    artName: "Circley",
    pageLink: "./Art/Tranjenny/indexjenny.html",
    imageLink: "./Art/Tranjenny/zerojenny.gif",
    author: "Tranjenny",
    githubLink: "https://github.com/Tranjenny",
  },
  {
    artName: "My Vietnam",
    pageLink: "./Art/nhbduy/index.html",
    imageLink: "./Art/nhbduy/my-vietnam.gif",
    author: "Hoang-Bao-Duy NGUYEN",
    githubLink: "https://github.com/nhbduy",
  },
  {
    artName: "Hactoberfest Bus",
    pageLink: "./Art/shahpranaf/index.html",
    imageLink: "./Art/shahpranaf/hacktoberfest_bus.gif",
    author: "Pranav Shah",
    githubLink: "https://github.com/shahpranaf",
  },
  {
    artName: "Hacktoberfest",
    pageLink: "./Art/robihid/index.html",
    imageLink: "./Art/robihid/hacktoberfest.png",
    author: "robihid",
    githubLink: "https://github.com/robihid",
  },
  {
    artName: "Hi there",
    pageLink: "./Art/Aki/index.html",
    imageLink: "./Art/Aki/giphy.gif",
    author: "Aki",
    githubLink: "https://github.com/akmalist",
  },
  {
    artName: "Hacktoberfest 2019!",
    pageLink: "./Art/RedSquirrrel/index.html",
    imageLink: "./Art/RedSquirrrel/index.html/animation.PNG",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Sliding text",
    pageLink: "./Art/Flattopz/index.html",
    imageLink: "./Art/Flattopz/SlidingText.gif",
    author: "Flattopz",
    githubLink: "https://github.com/hjpunzalan",
  },
  {
    artName: "Rainbow Color Changer",
    pageLink: "./Art/mmshr/index.html",
    imageLink: "./Art/mmshr/rainbow.gif",
    author: "mmosehauer",
    githubLink: "https://github.com/mmosehauer",
  },
  {
    artName: "World of Coding",
    pageLink: "./Art/tom_kn/coding.html",
    imageLink: "./Art/tom_kn/coding.gif",
    author: "Tamas Knisz",
    githubLink: "https://github.com/TamasKn",
  },
  {
    artName: "Initial Bounce",
    pageLink: "./Art/Juwana/initial.html",
    imageLink: "./Art/Juwana/InitialBounce.gif",
    author: "Juwana",
    githubLink: "https://github.com/JZerman2018",
  },
  {
    artName: "Atom",
    pageLink: "./Art/Teva/index.html",
    imageLink: "./Art/Teva/atom.gif",
    author: "Teva",
    githubLink: "https://github.com/TevaHenry",
  },
  {
    artName: "Be Awesome",
    pageLink: "./Art/TigerAsH/index.html",
    imageLink: "./Art/TigerAsH/be-awesome.jpg",
    author: "TigerAsH",
    githubLink: "https://github.com/TigerAsH94",
  },
  {
    artName: "Rainbow Colors",
    pageLink: "./Art/Sanjeev/index.html",
    imageLink: "./Art/Sanjeev/animation.gif",
    author: "Sanjeev Panday",
    githubLink: "https://github.com/Sanjeev-Panday",
  },
  {
    artName: "ZtM",
    pageLink: "./Art/thoyvo/index.html",
    imageLink: "./Art/thoyvo/ztm.gif",
    author: "Thoyvo",
    githubLink: "https://github.com/thoyvo",
  },
  {
    artName: "Fast Fishes",
    pageLink: "./Art/4ront/index.html",
    imageLink: "./Art/4ront/fishes.gif",
    author: "4rontender",
    githubLink: "https://github.com/RinatValiullov",
  },
  {
    artName: "Loading...",
    pageLink: "./Art/RedSquirrrel2/loading.html",
    imageLink: "./Art/RedSquirrrel2/loading.gif",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Animated Cube",
    pageLink: "./Art/Animated Cube/index.html",
    imageLink: "./Art/Animated Cube/cube.gif",
    author: "RedSquirrrel",
    githubLink: "https://github.com/RedSquirrrel",
  },
  {
    artName: "Calm Ubuntu",
    pageLink: "./Art/schupat/index.html",
    imageLink: "./Art/schupat/preview.gif",
    author: "schupat",
    githubLink: "https://github.com/schupat",
  },
  {
    artName: "Solar System",
    pageLink: "./Art/DSandberg93/index.html",
    imageLink: "./Art/DSandberg93/SolarSystem.gif",
    author: "DSandberg93",
    githubLink: "https://github.com/DSandberg93",
  },
  {
    artName: "Boo",
    pageLink: "./Art/VerityB/index.html",
    imageLink: "./Art/VerityB/boo.gif",
    author: "VerityB",
    githubLink: "https://github.com/VerityB",
  },
  {
    artName: "Hacktoberfest Ghost",
    pageLink: "./Art/cTahirih/index.html",
    imageLink: "./Art/cTahirih/ghost.png",
    author: "cTahirih",
    githubLink: "https://github.com/cTahirih",
  },
  {
    artName: "Clock",
    pageLink: "./Art/Abdul/index.html",
    imageLink: "./Art/Abdul/Clock.png",
    author: "Abdul Rahman",
    githubLink: "https://github.com/abdulrahman118",
  },
  {
    artName: "Loading Cube",
    pageLink: "./Art/andrearizzello/index.html",
    imageLink: "./Art/andrearizzello/index.gif",
    author: "Andrea Rizzello",
    githubLink: "https://github.com/andrearizzello",
  },
  {
    artName: "Wall Dropping Logo",
    pageLink: "./Art/shivams136/index.html",
    imageLink: "./Art/shivams136/walldrop.gif",
    author: "Shivam Sharma",
    githubLink: "https://github.com/ShivamS136",
  },
  {
    artName: "Infinite Race",
    pageLink: "./Art/levermanx/index.html",
    imageLink: "./Art/levermanx/anim.gif",
    author: "Levermanx",
    githubLink: "https://github.com/levermanx",
  },
  {
    artName: "Hover to Rotate Text",
    pageLink: "./Art/faiz_hameed/index.html",
    imageLink: "./Art/faiz_hameed/hackto.gif",
    author: "Faiz Hameed",
    githubLink: "https://github.com/faizhameed",
  },
  {
    artName: "HalloHacktober Greeting!",
    pageLink: "./Art/lusalga/index.html",
    imageLink: "./Art/lusalga/lu.gif",
    author: "Lucieni A. Saldanha",
    githubLink: "https://github.com/lusalga/",
  },
  {
    artName: "Time goes by",
    pageLink: "./Art/WolfgangKreminger/index.html",
    imageLink: "./Art/WolfgangKreminger/showcase.gif",
    author: "Wolfgang Kreminger",
    githubLink: "https://github.com/r4pt0s",
  },
  {
    artName: "Bouncing Text!",
    pageLink: "./Art/AbdulsalamAbdulrahman/index.html",
    imageLink: "./Art/AbdulsalamAbdulrahman/Bouncingtxt.gif",
    author: "Abdulsalam Abdulrahman",
    githubLink: "https://github.com/AbdulsalamAbdulrahman/",
  },
  {
    artName: "Simple Phone Animation",
    pageLink: "./Art/Lala/index.html",
    imageLink: "./Art/Lala/phone.gif",
    author: "Olamide Aboyeji",
    githubLink: "https://github.com/aolamide",
  },
  {
    artName: "Synthwave Sunset",
    pageLink: "./Art/brunobolting/index.html",
    imageLink: "./Art/brunobolting/synthwave-sunset.gif",
    author: "Bruno Bolting",
    githubLink: "https://github.com/brunobolting/",
  },
  {
    artName: "Kawaii Penguin",
    pageLink: "./Art/Brienyll/index.html",
    imageLink: "./Art/Brienyll/kawaiiPenguin.gif",
    author: "Brienyll",
    githubLink: "https://github.com/brienyll/",
  },
  {
    artName: "Happy Halloween",
    pageLink: "./Art/MatthewS/index.html",
    imageLink: "./Art/MatthewS/Spider.gif",
    author: "MatthewS",
    githubLink: "https://github.com/matthewstoddart/",
  },
  {
    artName: "Fan Art",
    pageLink: "./Art/m-perez33/index.html",
    imageLink: "./Art/m-perez33/cylon.gif",
    author: "Marcos Perez",
    githubLink: "https://github.com/m-perez33/",
  },
  {
    artName: "Animating Pot",
    pageLink: "./Art/Somechandra/index.html",
    imageLink: "./Art/Somechandra/pot.gif",
    author: "Somechandra",
    githubLink: "https://github.com/somechandra",
  },
  {
    artName: "Circles Circling",
    pageLink: "./Art/pikktorr/index.html",
    imageLink: "./Art/pikktorr/circles.gif",
    author: "pikktorr",
    githubLink: "https://github.com/pikktorr",
  },
  {
    artName: "Glitchy Szn",
    pageLink: "./Art/premdav/index.html",
    imageLink: "./Art/premdav/screenshot.png",
    author: "premdav",
    githubLink: "https://github.com/premdav",
  },
  {
    artName: "ZeroToMastery",
    pageLink: "./Art/Vzneers/index.html",
    imageLink: "./Art/Vzneers/gifzeroloading.gif",
    author: "TrinhMinhHieu",
    githubLink: "https://github.com/trinhminhhieu",
  },
  {
    artName: "Spacecraft-landing",
    pageLink: "./Art/DDuplinszki/index.html",
    imageLink: "./Art/DDuplinszki/Spacecraft-landing.gif",
    author: "DDuplinszki",
    githubLink: "https://github.com/DDuplinszki",
  },
  {
    artName: "Paw Prints",
    pageLink: "./Art/Tia/index.html",
    imageLink: "./Art/Tia/paw-prints.gif",
    author: "Tia Esguerra",
    githubLink: "https://github.com/msksfo",
  },
  {
    artName: "Hover-Scale",
    pageLink: "./Art/echowebid/index.html",
    imageLink: "./Art/echowebid/hover.gif",
    author: "echowebid",
    githubLink: "https://github.com/echowebid",
  },
  {
    artName: "mars",
    pageLink: "./Art/Courtney_Pure/index.html",
    imageLink: "./Art/Courtney_Pure/mars_screenshot.png",
    author: "Courtney Pure",
    githubLink: "https://github.com/courtneypure",
  },
  {
    artName: "Welcome HactoberFest",
    pageLink: "./Art/Dhaval/index.html",
    imageLink: "./Art/Dhaval/Welcome-Hacktoberfest.gif",
    author: "Dhaval Mehta",
    githubLink: "https://github.com/Dhaval1403",
  },
  {
    artName: "Aynonimation",
    pageLink: "./Art/Aynorica/aynorica.html",
    imageLink: "./Art/Aynorica/Aynonimation.png",
    author: "aynorica",
    githubLink: "https://github.com/aynorica",
  },
  {
    artName: "sun-to-moon",
    pageLink: "./Art/haider/index.html",
    imageLink: "./Art/haider/sun-moon.gif",
    author: "Haider",
    githubLink: "https://github.com/hyderumer",
  },
  {
    artName: "Animatron",
    pageLink: "./Art/animatron/index.html",
    imageLink: "./Art/animatron/trance.gif",
    author: "Andrei",
    githubLink: "https://github.com/aneagoie",
  },
  {
    artName: "Loader Circle",
    pageLink: "./Art/beaps/index.html",
    imageLink: "./Art/beaps/loader-circle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Doors",
    pageLink: "./Art/pauliax/index.html",
    imageLink: "./Art/pauliax/doors.gif",
    author: "pauliax",
    githubLink: "https://github.com/pauliax",
  },
  {
    artName: "Clock with pendulum",
    pageLink: "./Art/Pankaj/index.html",
    imageLink: "./Art/Pankaj/Clock_with_pendulum.gif",
    author: "Pankaj",
    githubLink: "https://github.com/prime417",
  },
  {
    artName: "Animatron",
    pageLink: "./Art/animatron/index.html",
    imageLink: "./Art/animatron/trance.gif",
    author: "Andrei",
    githubLink: "https://github.com/aneagoie",
  },
  {
    artName: "Loader Circle",
    pageLink: "./Art/beaps/index.html",
    imageLink: "./Art/beaps/loader-circle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Open Sourcerer",
    pageLink: "./Art/4rturd13/index.html",
    imageLink: "./Art/4rturd13/openSourcerer.gif",
    author: "4rturd13",
    githubLink: "https://github.com/4rturd13",
  },
  {
    artName: "Doors",
    pageLink: "./Art/pauliax/index.html",
    imageLink: "./Art/pauliax/doors.gif",
    author: "pauliax",
    githubLink: "https://github.com/pauliax",
  },
  {
    artName: "Loader Square",
    pageLink: "./Art/beaps2/square-loader.html",
    imageLink: "./Art/beaps2/square-loader.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Running Text",
    pageLink: "./Art/DevinEkadeni/running-text.html",
    imageLink: "./Art/DevinEkadeni/running-text.gif",
    author: "Devin Ekadeni",
    githubLink: "https://github.com/devinekadeni",
  },
  {
    artName: "Mystical-Hacktoberfest",
    pageLink: "./Art/Wayne/index.html",
    imageLink:
      "./Art/Wayne/hacktoberfest - Google Chrome 09 Oct 2019 21_12_32.png",
    author: "Wayne Mac Mavis",
    githubLink: "https://github.com/WayneMacMavis",
  },
  {
    artName: "ZTM Logo Animation",
    pageLink: "./Art/bk987/index.html",
    imageLink: "./Art/bk987/preview.gif",
    author: "Bilal Khalid",
    githubLink: "https://github.com/bk987",
  },
  {
    artName: "Pong",
    pageLink: "./Art/Carls13/index.html",
    imageLink: "./Art/Carls13/pong.jpg",
    author: "Carlos Hernandez",
    githubLink: "https://github.com/Carls13",
  },
  {
    artName: "ZTM Reveal",
    pageLink: "./Art/bk987-2/index.html",
    imageLink: "./Art/bk987-2/preview.gif",
    author: "Bilal Khalid",
    githubLink: "https://github.com/bk987",
  },
  {
    artName: "ZTM Family Animation",
    pageLink: "./Art/sballgirl11/animation.html",
    imageLink: "./Art/sballgirl11/ztm.gif",
    author: "Brittney Postma",
    githubLink: "https://github.com/sballgirl11",
  },
  {
    artName: "Phone Greetings",
    pageLink: "./Art/ann-dev/index.html",
    imageLink: "./Art/ann-dev/screenshot.png",
    author: "ann-dev",
    githubLink: "https://github.com/ann-dev",
  },
  {
    artName: "Triangle Slide",
    pageLink: "./Art/grieff/index.html",
    imageLink: "./Art/grieff/triangle-animation.gif",
    author: "Grieff",
    githubLink: "https://github.com/grieff",
  },
  {
    artName: "Neon ZTM",
    pageLink: "./Art/grieff/text.html",
    imageLink: "./Art/grieff/neonZTM.gif",
    author: "Grieff",
    githubLink: "https://github.com/grieff",
  },
  {
    artName: "Flip Card",
    pageLink: "./Art/FlipCard/index.html",
    imageLink: "./Art/FlipCard/ezgif.com-video-to-gif.gif",
    author: "Saurabh",
    githubLink: "https://github.com/Saurabh-FullStackDev",
  },
  {
    artName: "animationHalloween",
    pageLink: "./Art/mawais54013/index.html",
    imageLink: "./Art/mawais54013/Halloween.gif",
    author: "mawais54013",
    githubLink: "https://github.com/mawais54013",
  },
  {
    artName: "Hacktoberfest Letter Popups",
    pageLink: "./Art/jmt3559/index.html",
    imageLink: "https://media.giphy.com/media/RKSRPGiIsy1f3Ji3j1/giphy.gif",
    author: "Juan T.",
    githubLink: "https://github.com/jmtellez",
  },
  {
    artName: "Oscillation",
    pageLink: "./Art/Oscillation/index.html",
    imageLink: "./Art/Oscillation/oscillation.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "Letters flipUp",
    pageLink: "./Art/TerenceBiney/index.html",
    imageLink: "./Art/TerenceBiney/lettersanimate.gif",
    author: "Terence Biney",
    githubLink: "https://github.com/Tereflech17",
  },
  {
    artName: "Colors rectangle",
    pageLink: "./Art/beaps3/index.html",
    imageLink: "./Art/beaps3/colors-rectangle.gif",
    author: "beaps",
    githubLink: "https://github.com/beaps",
  },
  {
    artName: "Hinge",
    pageLink: "./Art/hereisfahad/index.html",
    imageLink: "./Art/hereisfahad/hinge.png",
    author: "Hereisfahad",
    githubLink: "https://github.com/hereisfahad",
  },
  {
    artName: "Animation",
    pageLink: "./Art/PaulBillings/animation.html",
    imageLink: "./Art/PaulBillings/animation.gif",
    author: "Paul Billings",
    githubLink: "https://github.com/paulbillings",
  },
  {
    artName: "Diminishing",
    pageLink: "./Art/Diminishing/index.html",
    imageLink: "./Art/Diminishing/diminishing.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "yin-yang",
    pageLink: "./Art/yin-yang/index.html",
    imageLink: "./Art/yin-yang/yin-yang.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "eggJiggle",
    pageLink: "./Art/eggJiggle/index.html",
    imageLink: "./Art/eggJiggle/eggJiggle.gif",
    author: "Nandhakumar",
    githubLink: "https://github.com/Nandhakumar7792",
  },
  {
    artName: "Aynonimation",
    pageLink: "./Art/Aynorica/aynorica.html",
    imageLink: "./Art/Aynorica/Aynonimation.png",
    author: "aynorica",
    githubLink: "https://github.com/aynorica",
  },
  {
    artName: "ZTM Family Animation",
    pageLink: "./Art/sballgirl11/index.html",
    imageLink: "./Art/sballgirl11/ztm.gif",
    author: "Brittney Postma",
    githubLink: "https://github.com/sballgirl11",
  },
  {
    artName: "Calm",
    pageLink: "./Art/TMax/index.html",
    imageLink: "./Art/TMax/Choas.gif",
    author: "Tanesha",
    githubLink: "https://github.com/Mainemirror",
  },
  {
    artName: "Eyes",
    pageLink: "./Art/Ltheory/main.html",
    imageLink: "./Art/Ltheory/eyes.gif",
    author: "Ltheory",
    githubLink: "https://github.com/Ltheory",
  },
  {
    artName: "Jelly!",
    pageLink: "./Art/Pete331/index.html",
    imageLink: "./Art/Pete331/jelly.png",
    author: "Pete331",
    githubLink: "https://github.com/Pete331",
  },
  {
    artName: "clock-animation",
    pageLink: "./Art/clock-animation/clock.html",
    imageLink: "./Art/clock-animation/clock.gif",
    author: "Alan sarluv",
    githubLink: "https://github.com/alansarluv",
  },
  {
    artName: "Slider",
    pageLink: "./Art/furqan/index.html",
    imageLink: "./Art/furqan/in.gif",
    author: "Furqan",
    githubLink: "https://github.com/furki911s",
  },
  {
    artName: "animated-birds",
    pageLink: "./Art/g-serban/animated-birds.html",
    imageLink: "./Art/g-serban/animated-birds.gif",
    author: "g-serban",
    githubLink: "https://github.com/g-serban",
  },
  {
    artName: "circle-become-square",
    pageLink: "./Art/chathura19/index.html",
    imageLink: "./Art/chathura19/chathura.gif",
    author: "Chathura Samarajeewa",
    githubLink: "https://github.com/ChathuraSam",
  },
  {
    artName: "page-flicker",
    pageLink: "./Art/neon-flights/page-flicker.html",
    imageLink: "./Art/neon-flights/page-flicker.gif",
    author: "neon-flights",
    githubLink: "https://github.com/neon-flights",
  },
  {
    artName: "Animate-Name",
    pageLink: "./Art/Natalina/index.html",
    imageLink: "./Art/Natalina/animatename.gif",
    author: "Natalina",
    githubLink: "https://github.com/Natalina13",
  },
  {
    artName: "Asteroids",
    pageLink: "./Art/hrafnkellbaldurs/index.html",
    imageLink: "./Art/hrafnkellbaldurs/asteroids.gif",
    author: "Hrafnkell Baldursson",
    githubLink: "https://github.com/hrafnkellbaldurs",
  },
  {
    artName: "Sliding-Paragraph",
    pageLink: "./Art/Prashant/index.html",
    imageLink: "./Art/Prashant/slidingparagraph.gif",
    author: "Prashant",
    githubLink: "https://github.com/Prashant2108",
  },
  {
    artName: "Rocket Ship",
    pageLink: "./Art/sdangoy/rocket-ship.html",
    imageLink: "./Art/sdangoy/Rocket-Ship-Animation.gif",
    author: "sdangoy",
    githubLink: "https://github.com/sdangoy",
  },
  {
    artName: "Spinner",
    pageLink: "./Art/Sayan/index.html",
    imageLink: "./Art/Sayan/spinner.gif",
    author: "ssayanm",
    githubLink: "https://github.com/ssayanm",
  },
  {
    artName: "swivel",
    pageLink: "./Art/tusharhanda/index.html",
    imageLink: "./Art/tusharhanda/gif.gif",
    author: "Tushar",
    githubLink: "https://github.com/tusharhanda",
  },
  {
    artName: "Hallows Eve",
    pageLink: "./Art/ShanClayton/hallowseve.html",
    imageLink: "./Art/ShanClayton/hallowhack.gif",
    author: "Shanaun Clayton",
    githubLink: "https://github.com/shanclayton",
  },
  {
    artName: "Contraption",
    pageLink: "./Art/Aravindh/contraption.html",
    imageLink: "./Art/Aravindh/contraption.gif",
    author: "Aravindh",
    githubLink: "https://github.com/Aravindh-SNR",
  },
  {
    artName: "Rings",
    pageLink: "./Art/Kuzmycz/rings.html",
    imageLink: "./Art/Kuzmycz/rings.gif",
    author: "Mark Kuzmycz",
    githubLink: "https://github.com/kuzmycz",
  },
  {
    artName: "Ghost",
    pageLink: "./Art/toserjude/index.html",
    imageLink: "./Art/toserjude/boo.JPG",
    author: "toserjude",
    githubLink: "https://github.com/toserjude",
  },
  {
    artName: "Gradient circle",
    pageLink: "./Art/brettl1991/index.html",
    imageLink: "./Art/brettl1991/animation.png",
    author: "Agnes Brettl",
    githubLink: "https://github.com/brettl1991",
  },
  {
    artName: "Bill Cipher",
    pageLink: "./Art/vitoriapena/index.html",
    imageLink: "./Art/vitoriapena/bill_cipher.gif",
    author: "Vitória Mendes",
    githubLink: "https://github.com/vitoriapena",
  },
  {
    artName: "Generate meaning",
    pageLink: "./Art/Atif4/index.html",
    imageLink: "./Art/Generate meaning.gif",
    author: "Atif Iqbal",
    githubLink: "https://github.com/atif-dev",
  },
  {
    artName: "Spooktime",
    pageLink: "./Art/AgneDJ/index.html",
    imageLink: "./Art/AgneDJ/spooktime.gif",
    author: "AgneDJ",
    githubLink: "https://github.com/AgneDJ",
  },
  {
    artName: "Gradient circle",
    pageLink: "./Art/brettl1991/index.html",
    imageLink: "./Art/brettl1991/animation.png",
    author: "Agnes Brettl",
    githubLink: "https://github.com/brettl1991",
  },
  {
    artName: "Bill Cipher",
    pageLink: "./Art/vitoriapena/index.html",
    imageLink: "./Art/vitoriapena/bill_cipher.gif",
    author: "Vitória Mendes",
    githubLink: "https://github.com/vitoriapena",
  },
  {
    artName: "Dizzy",
    pageLink: "./Art/antinomy/index.html",
    imageLink: "./Art/antinomy/logo-spin.gif",
    author: "Antinomezco",
    githubLink: "https://github.com/antinomezco",
  },
  {
    artName: "bounce",
    pageLink: "./Art/bounce/index.html",
    imageLink: "./Art/bounce/bounce.gif",
    author: "leelacanlale",
    githubLink: "https://github.com/leelacanlale",
  },
  {
    artName: "Bubbles",
    pageLink: "./Art/bubbles/Bubbles.html",
    imageLink: "./Art/bubbles/buubles.png",
    author: "michal",
    githubLink: "https://github.com/michalAim",
  },
  {
    artName: "Bar Slide",
    pageLink: "./Art/MikeVedsted/index.html",
    imageLink: "./Art/MikeVedsted/barslide.png",
    author: "Mike Vedsted",
    githubLink: "https://github.com/MikeVedsted",
  },
  {
    artName: "HacktoberFest-2019",
    pageLink: "./Art/Atif/index.html",
    imageLink: "./Art/Atif/HacktoberFest-19.gif",
    author: "Atif Iqbal",
    githubLink: "https://github.com/atif-dev",
  },
  {
    artName: "Text Animation",
    pageLink: "./Art/Divya/index.html",
    imageLink: "./Art/Divya/screenshot.png",
    author: "Divya",
    githubLink: "https://github.com/DivyaPuri25",
  },
  {
    artName: "HacktoberFest-2019-Entry",
    pageLink: "./Art/nunocpnp/index.html",
    imageLink: "./Art/nunocpnp/sample_image.jpg",
    author: "Nuno Pereira",
    githubLink: "https://github.com/nunocpnp",
  },
  {
    artName: "HacktoberFest 2019",
    pageLink: "./Art/AbdussamadYisau/index.html",
    imageLink: "./Art/AbdussamadYisau/Screenshot.png",
    author: "Abdussamad Yisau",
    githubLink: "https://github.com/AbdussamadYisau",
  },
  {
    artName: "squareMagic",
    pageLink: "./Art/Rajnish-SquareMagic/index.html",
    imageLink: "./Art/Rajnish-SquareMagic/squareMagic.png",
    author: "Rajnish Kr Singh",
    githubLink: "https://github.com/RajnishKrSingh",
  },
  {
    artName: "Blinking Hacktober",
    pageLink: "./Art/Atif2/index.html",
    imageLink: "./Art/Blinking hacktober.gif",
    author: "Atif Iqbal",
    githubLink: "https://github.com/atif-dev",
  },
  {
    artName: "Robodance",
    pageLink: "./Art/robodance/index.html",
    imageLink: "./Art/robodance/robodance.gif",
    author: "Thomas",
    githubLink: "https://github.com/mahlqvist",
  },
  {
    artName: "Sliding hacktober",
    pageLink: "./Art/Atif3/index.html",
    imageLink: "./Art/Atif3/sliding hacktober.gif",
    author: "Atif Iqbal",
    githubLink: "https://github.com/atif-dev",
  },
  {
    artName: "like-animation",
    pageLink: "./Art/gibas79/like-animation.html",
    imageLink: "./Art/gibas79/like-animation.gif",
    author: "Gilberto Guimarães",
    githubLink: "https://github.com/gibas79",
  },
  {
    artName: "ZTM animation",
    pageLink: "./Art/ZTManimation/index.html",
    author: "damniha",
    imageLink: "./Art/ZTManimation/ZTM_animation.gif",
    githubLink: "https://github.com/damniha",
  },
  {
    artName: "Double Helix",
    pageLink: "./Art/KeenanNunesVaz/index.html",
    imageLink: "./Art/KeenanNunesVaz/double-helix.gif",
    author: "KeenanNV",
    githubLink: "https://github.com/KeenanNunesVaz",
  },
  {
    artName: "October",
    pageLink: "./Art/fprokofiev/index.html",
    imageLink: "./Art/fprokofiev/october.gif",
    author: "Fyodor Prokofiev",
    githubLink: "https://github.com/fprokofiev",
  },
  {
    artName: "Circle CSS",
    pageLink: "./Art/pXxcont/index.html",
    imageLink: "./Art/pXxcont/circlecss.png",
    author: "fzpX",
    githubLink: "https://github.com/fzpX",
  },
  {
    artName: "Asterisk Formation",
    pageLink: "./Art/NorahJC/index.html",
    imageLink: "./Art/NorahJC/asterisk-formation.gif",
    author: "NorahJC",
    githubLink: "https://github.com/norahjc",
  },
  {
    artName: "Bouncing CSS",
    pageLink: "./Art/Tina-Hoang/aniframe.html",
    imageLink: "./Art/Tina-Hoang/bounce.png",
    author: "Tina",
    githubLink: "https://github.com/nnh242",
  },
  {
    artName: "Ghost Balls",
    pageLink: "./Art/ghostBalls/index.html",
    imageLink: "./Art/ghostBalls/balls.png",
    author: "Beatriz Delmiro",
    githubLink: "https://github.com/biadelmiro",
  },
  {
    artName: "Walking Guy",
    pageLink: "./Art/walking-guy/index.html",
    imageLink: "./Art/walking-guy/video_gif.gif",
    author: "Rahulkumar Jha",
    githubLink: "https://github.com/Rahul240499",
  },
  {
    artName: "Hover Neon Animation",
    pageLink: "./Art/edjunma/index.html",
    imageLink: "./Art/edjunma/ejm-neon.gif",
    author: "edjunma",
    githubLink: "https://github.com/edjunma",
  },
  {
    artName: "Last In First Out Animation",
    pageLink: "./Art/Stryker/index.html",
    imageLink: "./Art/Stryker/zero-to-mastery-lifo-animation.gif",
    author: "Stryker Stinnette",
    githubLink: "https://github.com/StrykerKent",
  },
  {
    artName: "Happy Diwali Animation",
    pageLink: "./Art/Apoorva/index.html",
    imageLink: "./Art/Apoorva/Screen.gif",
    author: "Apoorva",
    githubLink: "https://github.com/apoorvamohite",
  },
  {
    artName: "Heart Beat",
    pageLink: "./Art/naveen-ku/Heart shape.html",
    imageLink: "./Art/naveen-ku/Heart shape.gif",
    author: "naveen-ku",
    githubLink: "https://github.com/naveen-ku",
  },
  {
    artName: "Smoky Text",
    pageLink: "./Art/smoky-text/index.html",
    imageLink: "./Art/smoky-text/smoky_text_gif.gif",
    author: "Rahulkumar Jha",
    githubLink: "https://github.com/Rahul240499",
  },
  {
    artName: "Rainbow and Clouds",
    pageLink: "./Art/rainbowclouds/index.html",
    imageLink: "./Art/rainbowclouds/rainbowclouds.gif",
    author: "isasimoo",
    githubLink: "https://github.com/isasimo",
  },
  {
    artName: "Peek a boo!",
    pageLink: "./Art/Virtual1/index.html",
    imageLink: "./Art/Virtual1/HappyHalloween.gif",
    author: "Jessica Erasmus",
    githubLink: "https://github.com/Virtual1",
  },
  {
    artName: "prashantM1",
    pageLink: "./Art/prashantM1/heart.html",
    imageLink: "./Art/prashantM1/heart.gif",
    author: "Prashant Maurya",
    githubLink: "https://github.com/prashantmaurya228",
  },

  {
    artName: "prashantM2",
    pageLink: "./Art/prashantM2/block.html",
    imageLink: "./Art/prashantM2/block.gif",
    author: "Prashant Maurya",
    githubLink: "https://github.com/prashantmaurya228",
  },

  {
    artName: "prashantM3",
    pageLink: "./Art/prashantM3/ball.html",
    imageLink: "./Art/prashantM3/ball.gif",
    author: "Prashant Maurya",
    githubLink: "https://github.com/prashantmaurya228",
  },
  {
    artName: "SquareStar",
    pageLink: "./Art/shawn/index.html",
    imageLink: "./Art/shawn/square_star.gif",
    author: "shawn",
    github: "https://github.com/hk2014",
  },
  {
    artName: "prashantM4",
    pageLink: "./Art/prashantM4/boxsize.html",
    imageLink: "./Art/prashantM4/boxsize.gif",
    author: "Prashant Maurya",
    githubLink: "https://github.com/prashantmaurya228",
  },
  {
    artName: "Happy hacking",
    pageLink: "https://github.com/szulima",
    imageLink: "./Art/szulima/hacking.gif",
    author: "szulima",
    githubLink: "https://github.com/szulima",
  },
  {
    artName: "ColorBomb",
    pageLink: "./Art/ColorBomb/index.html",
    imageLink: "./Art/ColorBomb/ztm.gif",
    author: "Rahulm2310",
    github: "https://github.com/Rahulm2310",
  },
  {
    artName: "Traffic Lights",
    pageLink: "./Art/Harry/index.html",
    imageLink: "./Art/Harry/lights.gif",
    author: "Harry",
    githubLink: "https://github.com/legenhairy",
  },
  {
    artName: "Glowing Text",
    pageLink: "./Art/glowing-text/index.html",
    imageLink: "./Art/glowing-text/glowing_text_gif.gif",
    author: "Rahulkumar Jha",
    githubLink: "https://github.com/Rahul240499",
  },
  {
    artName: "Ghost Stealth Text",
    pageLink: "./Art/Alara Joel/index.html",
    imageLink: "./Art/Alara Joel/stealth ghost.png",
    author: "Alara Joel",
    githubLink: "https://github.com/stealthman22",
  },
  {
    artName: "Cactus Balloon",
    pageLink: "./Art/cactus/index.html",
    imageLink: "./Art/cactus/catus.gif",
    author: "Ana Paula Lazzarotto de Lemos",
    githubLink: "https://github.com/anapaulalemos",
  },
  {
    artName: "Random Color Change",
    pageLink: "./Art/toto-titan-developer/index.html",
    imageLink: "./Art/toto-titan-developer/RandomColorChange.png",
    author: "Wyatt Henderson",
    githubLink: "https://github.com/toto-titan-developer",
  },
  {
    artName: "Trial",
    pageLink: "./Art/dhennisCssAnimation/index.html",
    imageLink: "./Art/dhennisCssAnimation/focusOnTheGood",
    author: "Dhennis Lim",
    github: "https://github.com/DhennisDavidLim",
  },
  {
    artName: "Rectangular Butterfly",
    pageLink: "./Art/muzak-mmd/index.html",
    imageLink: "./Art/muzak-mmd/butterfly.gif",
    author: "Mbarak",
    github: "https://github.com/muzak-mmd",
  },
  {
    artName: "Simple Text Animation",
    pageLink: "./Art/LordZeF/index.html",
    imageLink: "./Art/LordZeF/Text-animation.gif",
    author: "Lord ZeF",
    github: "https://github.com/LordZeF",
  },
  {
    artName: "Spinning Japanese",
    pageLink: "./Art/nihongo/index.html",
    imageLink: "./Art/nihongo/nihongo.gif",
    author: "Mike W",
    github: "https://github.com/mikewiner",
  },
  {
    artName: "Sun",
    pageLink: "./Art/Yj/index.html",
    imageLink: "./Art/Yj/sun.gif",
    author: "Youjung",
    github: "https://github.com/rose07a",
  },
  {
    artName: "Guy's",
    pageLink: "./Art/Guy's/index.html",
    imageLink: "",
    author: "Guy",
    github: "https://github.com/Guy3890",
  },
  {
    artName: "animation-text",
    pageLink: "./Art/animation-text/index.html",
    imageLink: "./Art/",
    author: "alexzemz",
    github: "https://github.com/alexzemz",
  },
  {
    artName: "Practice",
    pageLink: "./Art/SkiingOtter/index.html",
    imageLink: "",
    author: "SkiingOtter",
    github: "https://github.com/SkiingOtter",
  },
  {
    artName: "djdougan",
    pageLink: "./Art/djdougan/index.html",
    imageLink: "./Art/djdougan/css-mouseover-effect.png",
    author: "douglas dougan",
    github: "https://github.com/djdougan",
  },
  {
    artName: "Animated Background",
    pageLink: "./Art/Xarasho-Background/index.html",
    imageLink: "",
    author: "Alex Xarasho",
    github: "https://github.com/Xarasho",
  },
  {
    artName: "CarvalhoAnimation",
    pageLink: "./Art/CarvalhoAnimation/index.html",
    imageLink: "./Art/CarvalhoAnimation/Halloween.png",
    author: "Alexandre Carvalho",
    github: "https://github.com/AlexandreCarvalho1990",
  },
  {
    artName: "Flower Animation",
    pageLink: "./Art/aimee_flowerani/index.html",
    imageLink: "./Art/aimee_flowerani/flower.gif",
    author: "Aimee Hernandez",
    githubLink: "https://github.com/aimeehg",
  },
  {
    artName: "3D Spinning Rings",
    pageLink: "./Art/frostillicus/index.html",
    imageLink: "./Art/frostillicus/spinning_rings.png",
    author: "frostillicus",
    github: "https://github.com/frostillicus",
  },
  {
    artName: "Flexible Logo",
    pageLink: "./Art/Fab1ed/index.html",
    imageLink: "./Art/Fab1ed/flex.gif",
    author: "Fab1ed",
    github: "https://github.com/Fab1ed",
  },
  {
    artName: "Blinking Eye",
    pageLink: "./Art/BlinkingEye/index.html",
    imageLink: "./Art/BlinkingEye/blinkingeye.gif",
    author: "Pavel Perevozchikov",
    github: "https://github.com/papapacksoon",
  },
  {
    artName: "Zero-to-Logo",
    pageLink: "./Art/node.hg/index.html",
    imageLink: "./Art/node.hg/ztm.gif",
    author: "Harris Gomez",
    github: "https://github.com/harrisgomez",
  },
  {
    artName: "Mushyanimation",
    pageLink: "./Art/mushyanimation/index.html",
    imageLink: "./Art/mushyanimation/mush.gif",
    author: "mushymane",
    github: "https://github.com/mushymane",
  },
  {
    artName: "Flag",
    pageLink: "./Art/Batz005/index.html",
    imageLink: "./Art/Batz005/flag.gif",
    author: "Batz005",
    github: "https://github.com/Batz005",
  },
  {
    artName: "Wave",
    pageLink: "./Art/Wave_css/index.html",
    imageLink: "./Art/Wave_css/wave.gif",
    author: "Filippe",
    github: "https://github.com/filippebr",
  },
  {
    artName: "Preloader",
    pageLink: "./Art/mshuber1981/preloader.html",
    imageLink: "./Art/mshuber1981/preloader.gif",
    author: "Michael Huber",
    github: "https://github.com/mshuber1981",
  },
  {
    artName: "Simple Animate ZTM",
    pageLink: "./Art/Kweyku/index.html",
    imageLink: "./Art/Kweyku/proudZTM.gif",
    author: "Kweyku",
    github: "https://github.com/Kweyku",
  },
  {
    artName: "Heartbeat",
    pageLink: "./Art/lysychas/index.html",
    imageLink: "./Art/lysychas/heartshot.png",
    author: "lysychas",
    github: "https://github.com/lysychas",
  },
  {
    artName: "Hydrogen",
    pageLink: "./Art/elias/my-art.html",
    imageLink: "./Art/elias/hydrogen.gif",
    author: "tesolberg",
    github: "https://github.com/tesolberg",
  },
  {
    artName: "Cool-Transition",
    pageLink: "./Art/animatomang/html",
    videolink: "./Art/animatomang/smoke.mp4",
    author: "Syam",
    github: "https://github.com/blacktomang",
  },
  {
    artName: "Spinning Square",
    pageLink: "./Art/Spinning Square/index.html",
    imageLink: "./Art/Spinning Square/square.gif",
    author: "Fumi",
    github: "https://github.com/fumiadeyemi",
  },
  {
    artName: "letters-loading",
    pageLink: "./Art/franciscomelov/index.html",
    imageLink: "./Art/franciscomelov/franciscomelov.gif",
    author: "franciscomelov",
    githubLink: "https://github.com/franciscomelov",
  },
  {
    artName: "Moving Eyeball",
    pageLink: "./Art/AnathKantonda/index.html",
    imageLink: "./Art/AnathKantonda/movingeyeball.gif",
    author: "Anath",
    github: "https://github.com/anathkantonda",
  },
  {
    artName: "Flag Animation - Colomboalemán",
    pageLink: "./Art/Matic1909/index.html",
    imageLink: "./Art/Matic1909/flag.gif",
    author: "Nils Matic",
    githubLink: "https://github.com/matic1909",
  },
  {
    artName: "Pac-Man",
    pageLink: "./Art/Pac-Man/Pac-Man.html",
    imageLink: "./Art/Pac-Man/Pac-Man.gif",
    author: "Norbert",
    githubLink: "https://github.com/Bynor",
  },
  {
    artName: "Don't follow the light",
    pageLink: "./Art/cristobal-heiss/index.html",
    imageLink: "./Art/cristobal-heiss/css_animation.gif",
    author: "Cristobal Heiss",
    githubLink: "https://github.com/ceheiss",
  },
  {
    artName: "Eenimation",
    pageLink: "./Art/Eenimation/index.html",
    imageLink: "./Art/Eenimation/trance.gif",
    author: "Eejaz ishaq",
    githubLink: "https://github.com/eejazishaq",
  },
  {
    artName: "ripple button",
    pageLink: "./Art/monika-sahay/index.html",
    imageLink: "./Art/monika-sahay/screen-capture.gif",
    author: "monika sahay",
    githubLink: "https://github.com/monika-sahay",
  },
  {
    artName: "Animation",
    pageLink: "./Art/Albertomtferreira/index.html",
    imageLink: "./Art/Albertomtferreira/animation.gif",
    author: "Alberto Ferreira",
    githubLink: "https://github.com/albertomtferreira",
  },
  {
    artName: "sliding curtains",
    pageLink: "./Art/layoayeni/index.html",
    imageLink: "./Art/layoayeni/trance.gif",
    author: "Layo",
    githubLink: "https://github.com/layoayeni",
  },
  {
    artName: "Unlocked",
    pageLink: "./Art/confusionmatrix98/unlocked.html",
    imageLink: "./Art/confusionmatrix98/unlocked.gif",
    author: "confusionmatrix98",
    githubLink: "https://github.com/confusionmatrix98",
  },
  {
    artName: "Slovenian flag",
    pageLink: "./Art/Ivan's art/index.html",
    imageLink: "./Art/Ivan's art/Ivan-art.gif",
    author: "kljuni",
    githubLink: "https://github.com/kljuni",
  },
  {
    artName: "Police Siren",
    pageLink: "./Art/ShimShon1/policia.html",
    imageLink: "./Art/ShimShon1/police.gif",
    author: "ShimShon1",
    githubLink: "https://github.com/ShimShon1",
  },
  {
    artName: "Catch The UFO",
    pageLink: "./Art/A-UFO/index.html",
    imageLink: "./Art/A-UFO/catch-the-ufo.gif",
    author: "Dibakash",
    githubLink: "https://github.com/dibakash",
  },
  {
    artName: "dk649",
    pageLink: "./Art/dk649/index.html",
    imageLink: "./Art/dk649/circle.gif",
    author: "dk649",
    githubLink: "https://github.com/dk649",
  },
  {
    artName: "Catch The UFO",
    pageLink: "./Art/A-UFO/index.html",
    imageLink: "./Art/A-UFO/catch-the-ufo.gif",
    author: "Dibakash",
    githubLink: "https://github.com/dibakash",
  },
  {
    artName: "Beer",
    pageLink: "./Art/beer/index.html",
    imageLink: "./Art/beer/beer.gif",
    author: "CamJackson",
    githubLink: "https://github.com/CamJackson-Dev",
  },
  {
    artName: "1rotate",
    pageLink: "./Art/1rotate/index.html",
    imageLink: "./Art/1rotate/rotation.gif",
    author: "Himanshu Gawari",
    githubLink: "https://github.com/himanshugawari",
  },
  {
    artName: "Moving Box",
    pageLink: "./Art/JerylDEv/index.html",
    imageLink: "./Art/JerylDEv/movingbox.gif",
    author: "JerylDEv",
    githubLink: "https://github.com/JerylDEv",
  },
  {
    artName: "New move",
    pageLink: "./Art/NewMove/index.html",
    imageLink: "./Art/NewMove/NewMove.gif",
    author: "kzhecheva",
    githubLink: "https://github.com/kzhecheva",
  },
  {
    artName: "animatron",
    pageLink: "./Art/animatron/index.html",
    imageLink: "./Art/animatron/trance.gif",
  },
  {
    artName: "Swing",
    pageLink: "./Art/evangel/index.html",
    imageLink: "./Art/evangel/swing.gif",
    githubLink: "https://github.com/devevangel",
  },
  {
    artName: "rashid",
    pageLink: "./Art/rashid/index.html",
    imageLink: "./Art/rashid/DNA.gif",
    author: "Rashid Makki",
    githubLink: "https://github.com/rashidmakki",
  },
  {
    artName: "queer quarantine",
    pageLink: "./Art/animatron/queer.html",
    imageLink: "./Art/animatron/queer.gif",
  },
  {
    artName: "Animatron",
    pageLink: "./Art/animatron/index.html",
    imageLink: "./Art/animatron/trance.gif",
    author: "Cassandre Perron",
    githubLink: "https://github.com/cassandreperron",
  },
  {
    artName: "Sun Bursts",
    pageLink: "./Art/steveSchaner/index.html",
    imageLink: "./Art/steveSchaner/sunburst.gif",
    author: "Steve Schaner",
    githubLink: "https://github.com/sschaner",
  },
  {
    artName: "Shravan",
    pageLink: "./Art/Shravan/animation_shr_page.html",
    imageLink: "./Art/Shravan/animation_shr.gif",
    author: "Shravan Kumar",
    githubLink: "https://github.com/shravan1508",
  },
  {
    artName: "Jurassic Park",
    pageLink: "./Art/tvasari/index.html",
    imageLink: "./Art/tvasari/jurassic_park.gif",
    author: "Tommaso Vasari",
    githubLink: "https://github.com/tvasari",
  },
  {
    artName: "Bounce",
    pageLink: "./Art/samya/index.html",
    imageLink: "./Art/samya/samya.gif",
    author: "Samya Thakur",
    githubLink: "https://github.com/samyathakur",
  },
  {
    artName: "Egg_Loading",
    pageLink: "./Art/egg_loading/index.html",
    imageLink: "./Art/samya/egg_loading.gif",
    author: "Ulisse Dantas",
    githubLink: "https://github.com/ulissesnew",
  },
  {
    artName: "We stay at home to save lives",
    pageLink: "./Art/Shatabdi/index.html",
    imageLink: "./Art/Shatabdi/WE STAY AT HOME TO SAVE LIVES.gif",
    author: "Shatabdi Roy",
    githubLink: "https://github.com/RoyShatabdi",
  },
  {
    artName: "Egg_Loading",
    pageLink: "./Art/egg_loading/index.html",
    imageLink: "./Art/egg_loading/egg_loading.gif",
    author: "Ulisse Dantas",
    githubLink: "https://github.com/ulissesnew",
  },
  {
    artName: "We stay at home to save lives",
    pageLink: "./Art/Shatabdi/index.html",
    imageLink: "./Art/Shatabdi/WE STAY AT HOME TO SAVE LIVES.gif",
    author: "Shatabdi Roy",
    githubLink: "https://github.com/RoyShatabdi",
  },
  {
    artName: "Animatron",
    pageLink: "./Art/animatronky/index.html",
    imageLink: "./Art/animatronky/trance.gif",
    author: "kylenrich",
    githubLink: "https://github.com/kylenrich24",
  },
  {
    artName: "bouncing ball",
    pageLink: "./Art/alexgp/index.html",
    imageLink: "./Art/Alexgp/bouncegif.gif",
    author: "AlexGP257",
    githubLink: "https://github.com/Alexgp257",
  },
  {
    artName: "Cool Waves",
    pageLink: "./Art/RaulC/index.html",
    imageLink: "./Art/RaulC/coolwaves.gif",
    author: "Raul Contreras",
    githubLink: "https://github.com/rcc01",
  },
  {
    artName: "Snowfall",
    pageLink: "./Art/chaitali_snowfall/index.html",
    imageLink: "./Art/chaitali_snowfall/snowgif.gif",
    author: "Chaitali",
    githubLink: "https://github.com/chaitali-more",
  },
  {
    artName: "Rotate Circle",
    pageLink: "./Art/dimor/animation.html",
    imageLink: "./Art/dimor/rotate.gif",
    author: "dimor",
    githubLink: "https://github.com/dimor",
  },
  {
    artName: "Hello world",
    pageLink: "./Art/warren8689/index.html",
    imageLink: "./Art/warren8689/screenshot.png",
    author: "Warren",
    githubLink: "https://github.com/warrren8689",
  },
  {
    artName: "360 Varial Kickflip",
    pageLink: "./Art/DICHAMOTO/index.html",
    imageLink: "./Art/DICHAMOTO/360_Varial_Kickflip.gif",
    author: "DICHAMOTO",
    githubLink: "https://github.com/DICHAMOTO",
  },
  {
    artName: "Crazy Square",
    pageLink: "./Art/colorSquare/index.html",
    imageLink: "./Art/colorSquare/colorsquare.gif",
    author: "TiagoChicoo",
    githubLink: "https://github.com/tiagochicoo",
  },
  {
    artName: "Alexhover",
    pageLink: "./Art/Alexhover/index.html",
    imageLink: "./Art/Alexhover/Alexhover.gif",
    author: "Alex",
    githubLink: "https://github.com/alesgainza",
  },
  {
    artName: "Imperial CSS Driod",
    pageLink: "./Art/Imperial_CSS_Driod/index.html",
    imageLink: "./Art/Imperial_CSS_Driod/ImperialDriod.gif",
    author: "Captian-Rocket",
    githubLink: "https://github.com/captian-rocket",
  },
  {
    artName: "HamidAnime",
    pageLink: "./Art/HamidAnime/index.html",
    imageLink: "./Art/HamidAnime/Capture.gif",
    author: "Hamid",
    githubLink: "https://github.com/HamidGoudarzi1988",
  },
  {
    artName: "Imperial CSS Driod",
    pageLink: "./Art/Imperial_CSS_Driod/index.html",
    imageLink: "./Art/Imperial_CSS_Driod/ImperialDriod.gif",
    author: "Captian-Rocket",
    githubLink: "https://github.com/captian-rocket",
  },
  {
    artName: "Mario Game",
    pageLink: "./Art/emmeiwhite/index.html",
    imageLink: "./Art/emmeiwhite/mario-game.gif",
    author: "Emmeiwhite",
    githubLink: "https://github.com/emmeiwhite",
  },
  {
    artName: "360 Varial Kickflip",
    pageLink: "./Art/DICHAMOTO/index.html",
    imageLink: "./Art/DICHAMOTO/360_Varial_Kickflip.gif",
    author: "DICHAMOTO",
    githubLink: "https://github.com/DICHAMOTO",
  },
  {
    artName: "Bouncer the Bouncy Box",
    pageLink: "./Art/RussD/index.html",
    imageLink: "./Art/RussD/bouncer-the-bouncy-box.png",
    author: "Russell",
    githubLink: "https://github.com/rdyer07",
  },
  {
    artName: "3D Infinite Loop Sprites Cards",
    pageLink: "./Art/luiavag/index.html",
    imageLink: "./Art/luiavag/luiavag_3D_Infinite_Loop.gif",
    author: "LuVAGu",
    githubLink: "https://github.com/luiavag",
  },
  {
    artName: "Star Wars",
    pageLink: "./Art/ChiragAgarwal/index.html",
    imageLink: "./Art/ChiragAgarwal/star_wars.gif",
    author: "Chirag Agarwal",
    githubLink: "https://github.com/chiragragarwal",
  },
  {
    artName: "ImageGallery",
    pageLink: "./Art/Hoverimage/index.html",
    imageLink: "./Art/Hoverimage/hoverimage.gif",
    author: "Siddhant Jain",
    githubLink: "https://github.com/Sid-web6306",
  },
  {
    artName: "characterwalking",
    pageLink: "./Art/characterwalkingChetan/index.html",
    imageLink: "./Art/characterwalkingChetan/image.png",
    author: "Chetan Muliya",
    githubLink: "https://github.com/chetanmuliya",
  },
  {
    artName: "Grow",
    pageLink: "./Art/octavioLafourcade/index.html",
    imageLink: "./Art/octavioLafourcade/animation.gif",
    author: "Octavio Lafourcade",
    githubLink: "https://github.com/tavolafourcade",
  },
  {
    artName: "Slats",
    pageLink: "./Art/Sagaquisces/index.html",
    imageLink: "./Art/Hoverimage/slats.gif",
    author: "Michael David Dunlap",
    githubLink: "https://github.com/sagaquisces",
  },
  {
    artName: "Coffee",
    pageLink: "./Art/animate-coffee/index.html",
    imageLink: "./Art/animate-coffee/ezgif.com-video-to-gif.gif",
    author: "Elise Welch",
    githubLink: "https://github.com/EliseWelch",
  },
  {
    artName: "Blended",
    pageLink: "./Art/Pro-animate/index.html",
    imageLink: "./Art/Pro-animate/Blended.gif",
    author: "Promise Nwafor",
    githubLink: "https://github.com/emPro-source",
  },
  {
    artName: "sproutseeds",
    pageLink: "./Art/sproutseeds/index.html",
    imageLink: "https://codepen.io/_Sabine/pen/yGGLON",
    author: "_Sabine",
  },
  {
    artName: "aninikhil",
    pageLink: "./Art/aninikhil/index.html",
    imageLink: "./Art/aninikhil/nik.jpg",
    author: "Nikhil N G",
    githubLink: "https://github.com/nikhilng99",
  },
  {
    artName: "Playballs",
    pageLink: "./Art/playballs/index.html",
    imageLink: "./Art/playballs/playballs.gif",
    author: "Omar Jabaly",
    githubLink: "https://github.com/Omarjabaly",
  },
  {
    artName: "simpleAnimation",
    pageLink: "./Art/cazabe/index.html",
    imageLink: "./Art/cazabe/mrRobot.png",
    author: "cazabe",
    githubLink: "https://github.com/cazabe",
  },
  {
    artName: "Dragon",
    pageLink: "./Art/Dragon/index.html",
    imageLink: "./Art/Joy/smallDragon.gif",
    author: "nikicivan",
    githubLink: "https://github.com/nikicivan",
  },
  {
    artName: "TypingAnimation",
    pageLink: "./Art/yogi_the_bear/index.html",
    imageLink: "./Art/yogi_the_bear/my_animation.gif",
    author: "yogev",
    githubLink: "https://github.com/yogevHenig",
  },
  {
    artName: "Mario Kart Animation",
    pageLink: "./Art/mario2/index.html",
    imageLink: "./Art/mario2/mario.png",
    author: "Sakshi Sinha",
    githubLink: "https://github.com/sakshi-1",
  },
  {
    artName: "NarutoAnimation",
    pageLink: "./Art/Tgoslee/index.html",
    imageLink: "./Art/Tgoslee/Naruto.gif",
    author: "Trenisha",
    githubLink: "https://github.com/tgoslee",
  },
  {
    artName: "Jackony",
    pageLink: "./Art/Yaseen_Mohammed/index.html",
    imageLink: "./Art/Yaseen_Mohammed/pichatcho.gif",
    author: "Yaseen_Mohammed",
    githubLink: "https://yaseenaiman.github.io/",
  },
  {
    artName: "DVRU",
    pageLink: "./Art/dvru/index.html",
    imageLink: "./Art/dvru/dvru.gif",
    author: "dvru",
    githubLink: "https://github.com/dvru",
  },
  {
    artName: "Coulisse",
    pageLink: "./Art/Ayoubahida/index.html",
    imageLink: "./Art/Ayoubahida/coulisseAnimation.gif",
    author: "Ayoubahida",
    githubLink: "https://github.com/Ayoubahida",
  },
  {
    artName: "TextAnimation",
    pageLink: "./Art/TextAnimation/index.html",
    imageLink: "./Art/TextAnimation/welcome.gif",
    author: "waleed",
    githubLink: "https://github.com/waleed-1993",
  },
  {
    artName: "Animatron",
    pageLink: "./Art/Animatron/index.html",
    imageLink: "./Art/Joy/trance.gif",
    author: "farhan",
    githubLink: "https://github.com/fnahmad",
  },
  {
    artName: "Sky",
    pageLink: "./Art/marijapanic/index.html",
    imageLink: "./Art/marijapanic/clouds.gif",
    author: "marijapanic",
    githubLink: "https://github.com/marijapanic",
  },
  {
    artName: "GreenFunnel",
    pageLink: "./Art/GreenFunnel/index.html",
    imageLink: "./Art/GreenFunnel/green-funnel.gif",
    author: "sergiorra",
    githubLink: "https://github.com/sergiorra",
  },
];

// +--------------------------------------------------------------------------------+
// +                                                                                +
// +                  YOU DO NOT NEED TO CHANGE ANYTHING BELOW THIS                 +
// +                                                                                +
// +--------------------------------------------------------------------------------+

// Creates cards from the array above
// You don't need to modify this
let contents = [];
Shuffle(cards).forEach((c) => {
  contents.push([
    `<li class="card">` +
      `<a href='${c.pageLink}'>` +
      `<img class="art-image" src='${c.imageLink}' alt='${c.artName}' />` +
      `</a>` +
      `<div class="flex-content">` +
      `<a href='${c.pageLink}'><h3 class="art-title">${c.artName}</h3></a>` +
      `<p class='author'><a href="${c.githubLink}" target="_blank"><i class="fab fa-github"></i> ${c.author}</a> </p>` +
      `</div>` +
      `</li>`,
  ]);
});

document.getElementById("cards").innerHTML = contents;

function Shuffle(o) {
  for (
    var j, x, i = o.length;
    i;
    j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x
  );
  return o;
}
