name: Generate Screenshots

on:
  push:
    branches:
      - master

jobs:
  screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history to ensure all commits are accessible

    # Install Puppeteer
    - name: Install Puppeteer
      run: npm install puppeteer

    # Install Sharp
    - name: Install Sharp
      run: npm install sharp

    # Run Puppeteer script to generate screenshots
    - name: Generate screenshots
      run: node generators/generateScreenshot.js

    - name: Commit and Push Screenshots
      run: |
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Check for changes
        git pull
        
        # Add changes
        git add Art/**/icon.png
        
        # Commit changes if there are any
        git commit -m "(CI) Screenshot Generation" || echo "No changes to commit"
        
        # Push changes
        git push